set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
# set window split
bind-key v split-window -h
bind-key b split-window

set -g renumber-windows on # automatically renumbers windows if gaps

# C-b is not acceptable -- Vim uses it
set-option -g prefix C-a
bind-key C-a last-window
# Start numbering at 1
set -g base-index 1

# Allows us to use C-a a <command> to send commands to a TMUX session inside 
# another TMUX session
bind-key a send-prefix

# Use vim keybinds in copy mode
set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -in -selection clipboard"

# hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# split panes
bind | split-window -h
bind - split-window -v

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key C command-prompt -p "Name of new window: " "new-window -n '%%'"

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded..."

# auto window rename
set-window-option -g automatic-rename

# Allow images to show in ssh session
set -s set-clipboard on

# Enable true color support
# set -g default-terminal "xterm-ghostty"
set -g default-terminal 'xterm-256color'

# Enable focus events (important for Kitty)
set -g focus-events on

# Allow passthrough of escape sequences
set -g allow-passthrough on
set -ga terminal-overrides ',*:Tc'

# Enable mouse support (optional but recommended)
set -g mouse on

# Ensure proper terminal type for SSH sessions
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM_PROGRAM TERM_PROGRAM_VERSION"


# 'Default' Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# Theme (Gruvbox)
set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'dark256'
# Ressurect and Continuum
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @tpm-install-verbose 'on'
# TMUX Vim Navigator
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @vim_navigator_mapping_left "C-Left C-h"  # use C-h and C-Left
set -g @vim_navigator_mapping_right "C-Right C-l"
set -g @vim_navigator_mapping_up "C-k"
set -g @vim_navigator_mapping_down "C-j"
set -g @vim_navigator_mapping_prev ""  # removes the C-\ binding
# Open Links in TMUX
set -g @plugin 'tmux-plugins/tmux-open'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
